In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

In [4]:
text="""경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다\n"""

In [5]:
t = Tokenizer()
t.fit_on_texts([text])
vocab_size = len(t.word_index)+1
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 12


In [7]:
print(t.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [14]:
sequences = list()
for line in text.split('\n'):
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)
        
print('학습에 사용할 샘플의 개수는 : %d' %len(sequences))

학습에 사용할 샘플의 개수는 : 11


In [15]:
print(sequences)

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


In [16]:
max_len = max(len(l) for l in sequences)
print('샘플 최대의 길이는 : %d' %max_len)

샘플 최대의 길이는 : 6


In [17]:
sequences = pad_sequences(sequences, maxlen = max_len, padding = 'pre')

In [18]:
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [19]:
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]

In [20]:
print(X)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]


In [21]:
print(y)

[ 3  1  4  5  1  7  1  9 10  1 11]


In [22]:
y = to_categorical(y, num_classes = vocab_size)

In [23]:
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [25]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length = max_len-1))
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation = 'softmax'))
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
model.fit(X, y, epochs = 200, verbose = 2)

Train on 11 samples
Epoch 1/200
11/11 - 1s - loss: 2.5032 - accuracy: 0.0909
Epoch 2/200
11/11 - 0s - loss: 2.4886 - accuracy: 0.0909
Epoch 3/200
11/11 - 0s - loss: 2.4741 - accuracy: 0.1818
Epoch 4/200
11/11 - 0s - loss: 2.4594 - accuracy: 0.3636
Epoch 5/200
11/11 - 0s - loss: 2.4445 - accuracy: 0.4545
Epoch 6/200
11/11 - 0s - loss: 2.4293 - accuracy: 0.4545
Epoch 7/200
11/11 - 0s - loss: 2.4137 - accuracy: 0.4545
Epoch 8/200
11/11 - 0s - loss: 2.3976 - accuracy: 0.4545
Epoch 9/200
11/11 - 0s - loss: 2.3809 - accuracy: 0.4545
Epoch 10/200
11/11 - 0s - loss: 2.3637 - accuracy: 0.4545
Epoch 11/200
11/11 - 0s - loss: 2.3457 - accuracy: 0.4545
Epoch 12/200
11/11 - 0s - loss: 2.3269 - accuracy: 0.3636
Epoch 13/200
11/11 - 0s - loss: 2.3072 - accuracy: 0.4545
Epoch 14/200
11/11 - 0s - loss: 2.2866 - accuracy: 0.5455
Epoch 15/200
11/11 - 0s - loss: 2.2651 - accuracy: 0.5455
Epoch 16/200
11/11 - 0s - loss: 2.2425 - accuracy: 0.4545
Epoch 17/200
11/11 - 0s - loss: 2.2189 - accuracy: 0.4545
Epo

Epoch 142/200
11/11 - 0s - loss: 0.2796 - accuracy: 1.0000
Epoch 143/200
11/11 - 0s - loss: 0.2731 - accuracy: 1.0000
Epoch 144/200
11/11 - 0s - loss: 0.2667 - accuracy: 1.0000
Epoch 145/200
11/11 - 0s - loss: 0.2606 - accuracy: 1.0000
Epoch 146/200
11/11 - 0s - loss: 0.2546 - accuracy: 1.0000
Epoch 147/200
11/11 - 0s - loss: 0.2487 - accuracy: 1.0000
Epoch 148/200
11/11 - 0s - loss: 0.2431 - accuracy: 1.0000
Epoch 149/200
11/11 - 0s - loss: 0.2375 - accuracy: 1.0000
Epoch 150/200
11/11 - 0s - loss: 0.2322 - accuracy: 1.0000
Epoch 151/200
11/11 - 0s - loss: 0.2270 - accuracy: 1.0000
Epoch 152/200
11/11 - 0s - loss: 0.2219 - accuracy: 1.0000
Epoch 153/200
11/11 - 0s - loss: 0.2170 - accuracy: 1.0000
Epoch 154/200
11/11 - 0s - loss: 0.2122 - accuracy: 1.0000
Epoch 155/200
11/11 - 0s - loss: 0.2075 - accuracy: 1.0000
Epoch 156/200
11/11 - 0s - loss: 0.2030 - accuracy: 1.0000
Epoch 157/200
11/11 - 0s - loss: 0.1986 - accuracy: 1.0000
Epoch 158/200
11/11 - 0s - loss: 0.1943 - accuracy: 1.00

In [33]:
def sentence_generation(model, t, current_word, n):
    init_word = current_word
    sentence = ''
    for _ in range(n):
        encoded = t.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen = 5, padding = 'pre')
        result = model.predict_classes(encoded, verbose = 0)
        
        for word, index in t.word_index.items():
            if index == result:
                break
        current_word = current_word + ' ' + word
        sentence = sentence + ' ' + word
    sentence = init_word+sentence
    return sentence

In [38]:
print(sentence_generation(model, t, '가는', 5))

가는 말이 고와야 오는 말이 곱다


In [40]:
import pandas as pd
from string import punctuation
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

In [41]:
df = pd.read_csv('ArticlesApril2017.csv')
df.head()

abstract                 articleID  ...  typeOfMaterial                                             webURL
0      NaN  58def1347c459f24986d7c80  ...            News  https://www.nytimes.com/2017/03/31/insider/nig...
1      NaN  58def3237c459f24986d7c84  ...           Op-Ed  https://www.nytimes.com/2017/03/31/opinion/and...
2      NaN  58def9f57c459f24986d7c90  ...       Editorial  https://www.nytimes.com/2017/03/31/opinion/ven...
3      NaN  58defd317c459f24986d7c95  ...            News  https://www.nytimes.com/2017/03/31/sports/ncaa...
4      NaN  58df09b77c459f24986d7ca7  ...            News  https://www.nytimes.com/2017/03/31/crosswords/...

[5 rows x 16 columns]

In [42]:
print('열의 개수 : ', len(df.columns))
print(df.columns)

열의 개수 :  16
Index(['abstract', 'articleID', 'articleWordCount', 'byline', 'documentType',
       'headline', 'keywords', 'multimedia', 'newDesk', 'printPage', 'pubDate',
       'sectionName', 'snippet', 'source', 'typeOfMaterial', 'webURL'],
      dtype='object')


In [43]:
df['headline'].isnull().values.any()

False

In [45]:
headline = []
headline.extend(list(df.headline.values))
headline[:5]

['Finding an Expansive View  of a Forgotten People in Niger',
 'And Now,  the Dreaded Trump Curse',
 'Venezuela’s Descent Into Dictatorship',
 'Stain Permeates Basketball Blue Blood',
 'Taking Things for Granted']

In [47]:
print('총 샘플의 수 : %d' %len(headline))

총 샘플의 수 : 886


In [48]:
headline = [n for n in headline if n!='Unkown']
print('노이즈 제거 후 샘플의 개수 : %d' %len(headline))

노이즈 제거 후 샘플의 개수 : 886


In [50]:
def repreprocessing(s):
    s = s.encode('utf-8').decode('ascii', 'ignore')
    return ''.join(c for c in s if c not in punctuation).lower()

text = [repreprocessing(x) for x in headline]
text[:5]

['finding an expansive view  of a forgotten people in niger',
 'and now  the dreaded trump curse',
 'venezuelas descent into dictatorship',
 'stain permeates basketball blue blood',
 'taking things for granted']

In [51]:
t = Tokenizer()
t.fit_on_texts(text)
vocab_size = len(t.word_index)+1
print('단어 집합의 크기 : %d' %vocab_size)

단어 집합의 크기 : 2423


In [52]:
sequences = list()

for line in text:
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)
        
sequences[:11]

[[170, 18],
 [170, 18, 666],
 [170, 18, 666, 368],
 [170, 18, 666, 368, 4],
 [170, 18, 666, 368, 4, 2],
 [170, 18, 666, 368, 4, 2, 667],
 [170, 18, 666, 368, 4, 2, 667, 171],
 [170, 18, 666, 368, 4, 2, 667, 171, 5],
 [170, 18, 666, 368, 4, 2, 667, 171, 5, 668],
 [6, 81],
 [6, 81, 1]]

In [63]:
index_to_word = {}
for key, value in t.word_index.items():
    index_to_word[value] = key
n = int(input())
print('빈도수 상위{}번째 단어 : {}'.format(n, index_to_word[n]))

1
빈도수 상위1번째 단어 : the


In [65]:
max_len = max(len(l) for l in sequences)
print('샘플의 최대 길이 : %d' %max_len)

샘플의 최대 길이 : 19


In [66]:
sequences = pad_sequences(sequences, maxlen = max_len, padding = 'pre')
print(sequences[:3])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 170
   18]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 170  18
  666]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 170  18 666
  368]]


In [67]:
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]

In [68]:
print(X)

[[   0    0    0 ...    0    0  170]
 [   0    0    0 ...    0  170   18]
 [   0    0    0 ...  170   18  666]
 ...
 [   0    0    0 ...   97 2421   58]
 [   0    0    0 ... 2421   58  366]
 [   0    0    0 ...   58  366   95]]


In [69]:
print(y)

[  18  666  368 ...  366   95 2422]


In [70]:
y = to_categorical(y, num_classes = vocab_size)

In [72]:
from tensorflow.keras.layers import LSTM

In [74]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length = max_len-1))
model.add(LSTM(128))
model.add(Dense(vocab_size, activation = 'softmax'))
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
model.fit(X,y, epochs = 200, verbose = 2)

Train on 4806 samples
Epoch 1/200
4806/4806 - 3s - loss: 7.4268 - accuracy: 0.0262
Epoch 2/200
4806/4806 - 2s - loss: 6.9088 - accuracy: 0.0306
Epoch 3/200
4806/4806 - 2s - loss: 6.7916 - accuracy: 0.0347
Epoch 4/200
4806/4806 - 2s - loss: 6.7051 - accuracy: 0.0320
Epoch 5/200
4806/4806 - 2s - loss: 6.6166 - accuracy: 0.0408
Epoch 6/200
4806/4806 - 2s - loss: 6.5173 - accuracy: 0.0470
Epoch 7/200
4806/4806 - 2s - loss: 6.4010 - accuracy: 0.0489
Epoch 8/200
4806/4806 - 2s - loss: 6.2698 - accuracy: 0.0470
Epoch 9/200
4806/4806 - 2s - loss: 6.1244 - accuracy: 0.0506
Epoch 10/200
4806/4806 - 2s - loss: 5.9786 - accuracy: 0.0506
Epoch 11/200
4806/4806 - 2s - loss: 5.8297 - accuracy: 0.0601
Epoch 12/200
4806/4806 - 2s - loss: 5.6875 - accuracy: 0.0643
Epoch 13/200
4806/4806 - 2s - loss: 5.5460 - accuracy: 0.0643
Epoch 14/200
4806/4806 - 2s - loss: 5.4086 - accuracy: 0.0737
Epoch 15/200
4806/4806 - 2s - loss: 5.2760 - accuracy: 0.0755
Epoch 16/200
4806/4806 - 2s - loss: 5.1482 - accuracy: 0.

Epoch 133/200
4806/4806 - 2s - loss: 0.5499 - accuracy: 0.8770
Epoch 134/200
4806/4806 - 2s - loss: 0.5404 - accuracy: 0.8822
Epoch 135/200
4806/4806 - 2s - loss: 0.5320 - accuracy: 0.8810
Epoch 136/200
4806/4806 - 2s - loss: 0.5236 - accuracy: 0.8847
Epoch 137/200
4806/4806 - 2s - loss: 0.5162 - accuracy: 0.8858
Epoch 138/200
4806/4806 - 2s - loss: 0.5083 - accuracy: 0.8862
Epoch 139/200
4806/4806 - 2s - loss: 0.5012 - accuracy: 0.8864
Epoch 140/200
4806/4806 - 2s - loss: 0.4934 - accuracy: 0.8885
Epoch 141/200
4806/4806 - 2s - loss: 0.4858 - accuracy: 0.8891
Epoch 142/200
4806/4806 - 2s - loss: 0.4783 - accuracy: 0.8899
Epoch 143/200
4806/4806 - 2s - loss: 0.4711 - accuracy: 0.8928
Epoch 144/200
4806/4806 - 2s - loss: 0.4654 - accuracy: 0.8922
Epoch 145/200
4806/4806 - 2s - loss: 0.4586 - accuracy: 0.8926
Epoch 146/200
4806/4806 - 2s - loss: 0.4514 - accuracy: 0.8951
Epoch 147/200
4806/4806 - 2s - loss: 0.4492 - accuracy: 0.8955
Epoch 148/200
4806/4806 - 2s - loss: 0.4394 - accuracy:

In [77]:
def sentence_generation(model, t, current_word, n):
    init_word = current_word
    sentence = ''
    for _ in range(n):
        encoded = t.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen = 18, padding = 'pre')
        result = model.predict_classes(encoded, verbose = 0)
        
        for word,index in t.word_index.items():
            if index == result:
                break
        current_word = current_word + ' ' + word
        sentence = sentence + ' ' + word
    sentence = init_word + sentence
    return sentence

In [78]:
print(sentence_generation(model, t, 'i', 10))

i survived a sarin gas attack in north korea airstrike dont


In [79]:
print(sentence_generation(model, t, 'how', 10))

how to be mindful when you are angry law industry day
